=== Snjezana33/PoslovnaInformatika/xsd/nalogZaPlacanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	targetNamespace="http://banka.com/nalogZaPlacanje" xmlns="http://banka.com/nalogZaPlacanje">
	<xs:element name="NalogZaPlacanje" type="NalogZaPlacanje"/>
	<xs:complexType name="NalogZaPlacanje">
		<xs:sequence>
			<xs:element name="ID_poruke">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Duznik-Nalogodavac">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Svrha_placanja">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Primalac-Poverilac">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Datum_naloga" type="xs:date"/>
			<xs:element name="Datum_valute" type="xs:date"/>
			<xs:element name="Racun_duznika">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="18"/>
						<xs:minLength value="18"/>
						<xs:pattern value="\d{18}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Model_zaduzenja">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Poziv_na_broj_zaduzenja">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="20"/>
						<xs:minLength value="1"/>
						<xs:pattern value="\d{1,20}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Racun_poverioca">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="18"/>
						<xs:minLength value="18"/>
						<xs:pattern value="\d{18}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Model_odobrenja">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Poziv_na_broj_odobrenja">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="20"/>
						<xs:minLength value="1"/>
						<xs:pattern value="\d{1,20}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Iznos">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="15"/>
						<xs:fractionDigits value="2"/>

					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Oznaka_valute">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3"/>
						<xs:minLength value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Hitno" type="xs:boolean"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Snjezana33/PoslovnaInformatika/xsd/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<NalogZaPlacanje xmlns="http://banka.com/nalogZaPlacanje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://banka.com/nalogZaPlacanje file:/C:/Users/Chakmi/Documents/PoslovnaProjekat/PoslovnaInformatikaBanka/xsd/nalogZaPlacanje.xsd">
    <ID_poruke>ID_poruke0</ID_poruke>
    <Duznik-Nalogodavac>Duznik-Nalogodavac0</Duznik-Nalogodavac>
    <Svrha_placanja>Svrha_placanja0</Svrha_placanja>
    <Primalac-Poverilac>Primalac-Poverilac0</Primalac-Poverilac>
    <Datum_naloga>2006-05-04</Datum_naloga>
    <Datum_valute>2006-05-04</Datum_valute>
    <Racun_duznika>000000000000000000</Racun_duznika>
    <Model_zaduzenja>0</Model_zaduzenja>
    <Poziv_na_broj_zaduzenja>0</Poziv_na_broj_zaduzenja>
    <Racun_poverioca>000000000000000000</Racun_poverioca>
    <Model_odobrenja>0</Model_odobrenja>
    <Poziv_na_broj_odobrenja>0</Poziv_na_broj_odobrenja>
    <Iznos>0.00</Iznos>
    <Oznaka_valute>Ozn</Oznaka_valute>
    <Hitno>false</Hitno>
</NalogZaPlacanje>
